name: send-macro-alert

on:
  schedule:
    # Cette ligne dit à GitHub de tourner à 07h00 UTC (soit 09h00 à Paris)
    - cron: '0 7 * * *'
  workflow_dispatch: # Garde ça pour pouvoir le lancer à la main si besoin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python macro_alert.py
